language: node_js
node_js: 12.18.3
cache: npm

install:
 npm install

os: window

script:
 npm run build

deploy:
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  apt_token: $GITHUB_TOKEN2  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master