language: node_js
node_js: 12.18.3
cache: npm

install:
 npm install

os: windows

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master